name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *' # 3시간마다
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git and Merge
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote add upstream https://github.com/prgrms-aibe-devcourse/AIBE3-Project1-Team04.git
          git fetch upstream --unshallow || true
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
